development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("redis://redistogo:a69ddb1549a504a2851ad255e6a4d679@pike.redistogo.com:10215/") { "redis://localhost:6379/1" } %>
  channel_prefix: NG_production

# redis: &redis
#   adapter: redis
#   url: redis://localhost:6379/1